logging:
  level:
    root: debug

# Set the port to the PORT environment variable
server:
  port: ${PORT:8080}
  jetty.:
    # TODO: Jetty server gets closed after timeout; temp fix: disable timeout
    connection-idle-timeout: -1

spring:
  cloud:
    gcp:
      datastore:
        project-id: gujrati-tailors-backend
        namespace: gujrati-tailors-backend
  main:
    allow-circular-references: true
  profiles:
    active:
      - local

jwt:
  secret: jwt-secret
